    CREATE TABLE DRONES.DRONES
    (
    ID NUMBER NOT NULL ,
    SERIAL_NUMBER VARCHAR2(100 BYTE) ,
    DEVICE_TYPE VARCHAR2(150 BYTE) ,
    WEIGHT NUMBER ,
    BATTERY_CAPACITY NUMBER ,
    STATE VARCHAR2(100 BYTE) ,
    CONSTRAINT DRONES_PK PRIMARY KEY (ID) ENABLE
    );

   CREATE SEQUENCE DRONES.DRONES_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    ORDER
    NOCYCLE;

   CREATE TABLE DRONES.MEDICATIONS
    (
    ID NUMBER NOT NULL ,
    NAME VARCHAR2(250 BYTE) ,
    CODE VARCHAR2(250 BYTE) ,
    WEIGHT NUMBER ,
    IMAGE_URL VARCHAR2(400 BYTE) ,
    DRONE_ID NUMBER ,
    CONSTRAINT MEDICATIONS_PK PRIMARY KEY (ID) ENABLE ,
    CONSTRAINT DRONES_FK FOREIGN KEY (DRONE_ID)
    REFERENCES DRONES.DRONES (ID) ENABLE
    );

    CREATE SEQUENCE DRONES.MEDICATIONS_SEQ
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    ORDER
    NOCYCLE;